### ISSUE TITLE
New module updates

### ISSUE THREAD

**Issue by nathansegers** [NMCT/mct-design#22]
A few of the MCT modules are already updated since the previous version of the website.
We should have a look at what needs to change.

Maybe we should ask for new descriptions for the existing modules as well?

**Comment by nathansegers** [comment]
Most modules have had their reworks.
Still to do:

- [ ] Wouter Gevaert --> Data Science, Machine Learning, Deep Learning, Advanced AI
- [ ] Stijn Walcarius --> Basic Programming, Advanced Programming & Maths
- [x] Dieter De Preester -->  IoT Cloud, Backend Development

**Comment by MLoth** [comment]
Zijn deze veranderingen doorgevoerd? Ik heb module updates enkel doorgestuurd naar jou en niet zelf aangepast.

**Comment by nathansegers** [comment]
Ja, alles is gestroomlijnd!
