### ISSUE TITLE
Curriculum rework

### ISSUE THREAD

**Issue by MLoth** [NMCT/mct-design#25]
Collega's, een paar zaken die moeten gebeuren tegen de volgende infodag.

Javascript
- [x] Modules popup opnieuw laten werken. We reflecteren de change in de url, tonen een popup.

Algemeen
- [x] Modules op andere plaatsen ook correct renderen (traject-pagina, @home, etc.).
- [x] Responsive correct renderen, per semester.

**Comment by nathansegers** [comment]
De traject-pagina is intussen in orde gebracht. Die is ook responsive genoeg, tot op 360px breedte.
De @home pagina moet nog aangepast worden, maar die pagina moet geheel bewerkt worden.
Ik check met Johan, en link door naar #23

**Comment by MLoth** [comment]
Het algemene curriculum is nu ook wat responsive gemaakt. Sowieso wil ik dit wel nog laten reviewen door @simoncoudeville.

**Comment by MLoth** [comment]
Daarnaast overweeg ik om het op staging te pushen, dan kunnen we al eens testen in onze test-omgeving. Sowieso is het nog niet af en moeten we alles eens goed testen 😄 .

**Comment by nathansegers** [comment]
Hier moeten we nog eens naar kijken:
Als er geen track gekozen is, staat die `::before` er niet meer bij...
![image](https://user-images.githubusercontent.com/29042774/173079601-a22ba2fd-6e1a-4e33-97c4-b2685ccaae5f.png)

- [x] Fixen van responsive Semester 5 & 6 in Responsive view

**Comment by nathansegers** [comment]
Vraagje:
Plaatsen we bij alle modules een gedeelte **description** en **tools** bij?
Dan kunnen we dat gestroomlijnd houden.

- [X] Description & Tools stroomlijnen

UPDATE 14/06. Overal werden Tools toegevoegd. De description is voor een andere keer. Die werd overal gehide waar het aanwezig was.

**Comment by nathansegers** [comment]
Kunnen we zorgen dat deze Permalink automatisch Semester 5 en 6 aanvult? Is ook handiger bij Auto-refreshes :-)
http://mct.be/programma/#profile-smart-xr-developer

- [x] Permalink automatisch semester invullen

**Comment by nathansegers** [comment]
Misschien kunnen we het een beetje dynamischer maken om in de toekomst het programma op meerdere pagina's te displayen (dynamische columns, rows, titles, choice-modules ...)

**Comment by nathansegers** [comment]
In responsive versie zijn de 3-SP modules niet meer verkleind. Dat moet nog eens gechecked worden

**Comment by MLoth** [comment]
Vroeger werden aan de hand van de url wel de keuzemodules ingevuld, zal ik eens moeten bekijken.
We overwegen om de studiepunten eventueel weer te geven per module, dan is de grootte op kleinere schermen ook niet zo erg meer denk ik. Kan je ook jouw changes op develop zetten? Dan kunnen we eens zien wat we nu al hebben.

**Comment by nathansegers** [comment]
https://feature-at-home--velvety-fudge-870292.netlify.app

**Comment by MLoth** [comment]
@simoncoudeville kjik jij nog even naar het algemene design? Ik denk dat de modules op het overzicht wel eens wat herzien kunnen worden?

**Comment by MLoth** [comment]
Design is bekeken. Klaar voor deze release.
