### ISSUE TITLE
Navigeren vanaf 404 pagina 

### ISSUE THREAD

**Issue by BoussonKarel** [NMCT/mct-design#6]
Wanneer je naar een pagina gaat die niet bestaat en terug wil keren naar een andere pagina (bijvoorbeeld waarom-mct) plakt hij /waarom-mct achter de pagina.

Je gaat bijvoorbeeld naar https://mct.be/paginabestaatniet/ (die niet bestaat) en klikt dan op Waarom mct, dan navigeert hij naar https://mct.be/paginabestaatniet/waarom-mct.

Bij het klikken op Ga naar de homepage, blijf je gewoon op https://mct.be/paginabestaatniet/

**Comment by simoncoudeville** [comment]
Inderdaad @BoussonKarel goed gezien. Bedankt om dit op deze manier te melden. We kijken er asap naar.

**Comment by MLoth** [comment]
Opgelost in de release van vandaag. Thanks @BoussonKarel!
